### ISSUE TITLE
help 么，plz，didn't show thumbnail in window 10

### ISSUE THREAD

**Issue by opencasting** [occivink/mpv-gallery-view#4]
try all night，and still just like this,the thumbnail didn't show up,wondering maybe the access authority is not enough？
![qq 20180419221910](https://user-images.githubusercontent.com/18377623/38998139-83f01626-4421-11e8-83da-b53e1cb44c4e.png)

**Comment by RomjanHossain** [comment]
Hey @occivink,
i'm getting the same error on Linux. As you answered , i've ffmpeg and ffprobe installed on my system. I've moved `playlist-view.lua`, `contact-sheet.lua`, `gallery-thumbgen.lua` and `lib.disable/gallery.lua` file in my scripts dir. I even created `.mpv_thumbs_dir` in my home directory. 

is there something that i'm missing here?

**Comment by occivink** [comment]
Hi @RomjanHossain,
`gallery.lua` needs to be copied together with the `lib.disable` folder, so your `.config/mpv/scripts` need to look like this
```
.
├── contact-sheet.lua
├── gallery-thumbgen-1.lua -> gallery-thumbgen.lua
├── gallery-thumbgen.lua
├── lib.disable
│   └── gallery.lua
├── playlist-view.lua
...
```
In this case, there is a symlink `gallery-thumbgen-1.lua`, which is optional. 
If that was already the case, make sure that you're running mpv from the commandline so that you can spot potential errors.

**Comment by RomjanHossain** [comment]
Thanks for replying my comment. 

My mpv scripts looks like the structure you have shown above. But it still is not working. 
here's my config -> https://github.com/RomjanHossain/configs/tree/master/mpv/scripts
