### ISSUE TITLE
thumbnails not apeairing :( 

### ISSUE THREAD

**Issue by omaru-ok** [occivink/mpv-gallery-view#41]
![image](https://user-images.githubusercontent.com/108952834/189760393-5ef308e2-8421-4bb1-a94b-61992d9039c0.png)
idk what to do  so please help 

and also threre is no error on CLI  after only this : 
![image](https://user-images.githubusercontent.com/108952834/189760477-f6de0588-0d1b-4f37-a048-c837be3a5f2e.png)

[portable_config.zip](https://github.com/occivink/mpv-gallery-view/files/9551897/portable_config.zip)
this is all my config. please not that all the things is named to my directory  :(

**Comment by omaru-ok** [comment]
> and also threre is no error on CLI after only this :
> ![image](https://user-images.githubusercontent.com/108952834/189760477-f6de0588-0d1b-4f37-a048-c837be3a5f2e.png)

this part idk what to do with mkdri_thumb?

**Comment by omaru-ok** [comment]
here is my mpv --version 
![Uploading image.png…]()

**Comment by occivink** [comment]
I think the issue is in your configuration files, the thumbs_dir variable more specifically. You uncommented the linux path, even though you're on windows. Also, there shouldn't be any quotes around the value of the variable. So all in all it should be

```
# on Windows:
thumbs_dir=C:\Users\oma\.cache\mpv\img
```

Also, you have an extra space before ` mkdir_thumbs=yes`, which is why the warning is printed.

**Comment by omaru-ok** [comment]
it worked :O
